dawidd6/action-download-artifact

- README.md
- main.js
Add support for retrieving the artifact from the most recent run if neither PR not commit are specified.
> #12 download artifact from the most recent run

- README.md
- action.yml
It also should be replaced in the repository description.
> ⚙️ A Github Action to download an artifact associated with given workflow and commit
> Replace "Github" with "GitHub"

- README.md
- action.yml
- main.js
This adds the branch option, it will act similar to `pr`, but instead will specify the branch name.
My usecase is that I always want to fetch an artifact from latest commit of `master`.
I tested locally by passing the params as `INPUT_*`, not sure if there are other ways.
```bash
$ INPUT_GITHUB_TOKEN=**redacted** INPUT_WORKFLOW=main.yml INPUT_NAME=openapi.json INPUT_REPO=RedHatInsights/policies-ui-backend INPUT_BRANCH=master INPUT_PATH=./  node main.js ==> Branch: master
==> Run: 168904055
==> Artifact: 11093736
==> Downloading: openapi.json.zip (23.61 kB)
inflating: openapi.json
```
```bash
$ INPUT_PR=foobar-pr INPUT_GITHUB_TOKEN=**redacted** INPUT_WORKFLOW=main.yml INPUT_NAME=openapi.json INPUT_REPO=RedHatInsights/policies-ui-backend INPUT_BRANCH=master INPUT_PATH=./  node main.js 
==> …
```
> Adds branch option

- action.yml
- main.js
This PR proposes to omit the artifact name and download all. This feature [was added in `actions/download-artifact`](https://github.com/actions/download-artifact#download-all-artifacts) as well. This is useful, for example, when you upload test reports from multiple split jobs, and summarize into one summary report. 
Here is an actual example, https://github.com/apache/spark/pull/29333 and [demo](https://github.com/HyukjinKwon/spark/runs/979902820) (I had to fork this repository to support this feature for now). It'd be nice if this repo has the feature.
I manually tested that it works in the demo above.
> Add the support of omitting artifact name

- .github/workflows/download.yml
- README.md
- action.yml
- main.js
This PR adds the `workflow_conclusion` input which can be used to specify a conclusion to search for in the recent runs.
This is useful when the artifacts are only uploaded when the workflow has a certain conclusion (for example when the run was successful).
In my case I do have dev & live deployments and only want to download artifacts from the latest & succesful dev deployment (in contrast to the latest run which might have failed)
> Add input to specify workflow conclusion

- README.md
- main.js
Closes #39
This allows for `workflow_completion` to be used as an additional filter with `branch`, `pr`, and `commit` to, for example, pull the last successful `master` build for a given workflow.
I ended up merging filtering by workflow status or completion and using this as filter in the API request as Github allows for both as the `status` filter:
https://developer.github.com/v3/actions/workflow-runs/#list-workflow-runs-for-a-repository
This allows us to skip filtering on that on the client-side.
Signed-off-by: Jesse Szwedko <jesse@szwedko.me>
> Allow workflow status filter to be used with branch, pr, and commit

- main.js
Currently, runs with over 30 artifacts only download the first 30 published. This PR adds support to page through all artifacts and download them accordingly.
> Add Pagination Support for Runs with >30 Artifacts

- main.js
This is the gist, what you think?
> Fix octokit returning weird results from listWorkflowRuns

- README.md
- action.yml
- main.js
For those who need to find a certain artifact knowing only its name.
> Search capability

- main.js
Unlike commit, branch is a parameter that is able to be filtered in the listWorkflowRuns request, so should reduce the number of potential matches that need to be iterated in the action.
> initialize branch with pr ref in addition to commit

- main.js
With empty filters (both "branch" and "event" set to empty strings) there are fewer results (please see the `watch` section on the left) than without specifying those filters. Related to https://github.com/dawidd6/action-download-artifact/issues/147.
> fix: do not set empty "branch" and "event" as filters

- .github/workflows/download.yml
- main.js
Now if we check unpacking, the zip file will be written according to the path specified, and not in the current folder
Fixes #168
> write zip file in path

- main.js
https://octokit.github.io/rest.js/v18#pulls
```js
import github from '@actions/github'
const client = github.getOctokit(token)
console.log(Object.keys(client), '←')
[
'request',  'graphql',
'log',      'hook',
'auth',     'rest',
'paginate'
] ←
console.log(Object.keys(client.rest), '←')
[
'actions',        'activity',
'apps',           'billing',
'checks',         'codeScanning',
'codesOfConduct', 'codespaces',
'dependabot',     'dependencyGraph',
'emojis',         'enterpriseAdmin',
'gists',          'git',
'gitignore',      'interactions',
'issues',         'licenses',
'markdown',       'meta',
'migrations',     'orgs',
'packages',       'projects',
'pulls',          'rateLimit',
'reactions',      'repos',
'search',         'secretScanning',
'teams',          'users'
] ←
```
> fix: fix octokit API invokes

- README.md
- action.yml
- main.js
`run_id`s are unique across workflows. So `workflow` id can be inferred from `run_id`.
And when neither `run_id` nor `workflow` are specified, current workflow can be used as a fallback.
Because `workflow` was previously a required input, this change shouldn't break any existing pipeline.
> Make 'workflow' input optional

- README.md
Given that the default value of the `workflow_conclusion` parameter is `success`, adding a description on how to ignore the conclusion altogether lets the user skip sipping through action source code or issues to figure out how to ignore it. Relates to #176.
> docs: describe how to ignore workflow_conclusion

- README.md
- action.yml
- main.js
this adds an additional input `if_no_files_found` which follows the semantic of `upload-artifact`.
the proposes solution in the issue comments to use `continue-on-error` has the ugly side-effect of showing a red warning in the workflow summary.
as I'm trying to train the developers to actually look at this summary in order to watch out for lint warning, they should not see red false-negative results in this list.
> feat: add additional input to define how to fail the action

- main.js
> Catch 'Artifact has expired' error

- .github/workflows/download.yml
- .github/workflows/upload.yml
- main.js
A second attempt at https://github.com/dawidd6/action-download-artifact/pull/205 after the first attempt had to be reverted.
More detail in https://github.com/dawidd6/action-download-artifact/issues/204.
> Add pagination to appropriate listWorkflowRunArtifacts call - take 2

- .github/workflows/download.yml
- main.js
Less results -> less pagination -> less API calls.
Maybe a bit faster even.
https://octokit.github.io/rest.js/v19#actions-list-workflow-runs
https://github.com/dawidd6/action-download-artifact/issues/226
> Use `commit` as `head_sha` to reduce number of API calls

- README.md
While setting up this action I ran into some confusion for the permissions it needed and only found the answer while looking at the [GitHub Actions Artifacts docs](https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#download-an-artifact). Would be nice to have this info in the readme of this repo as well.
> clarify permissions needed for github token

- .github/workflows/download.yml
- README.md
- action.yml
- main.js
Currently, either one artifact (by name) or all artifacts can be downloaded.
This adds option `filter`, which is used as a regular expression to match the artifact names. Only those artifacts where the name matches the regular expression are downloaded.
> Add regexp filter for artifact name

- README.md
- action.yml
- main.js
Contributes to https://github.com/dawidd6/action-download-artifact/issues/249
When working with the GitHub API, a run originating from a fork might still have the same branch name (e.g., master) as the parent repository. To filter out runs from forks, we check the `head_repository` attribute of the run. This attribute contains information about the repository where the head of the pull request is stored.
> fix: ignore forks

- README.md
- action.yml
- main.js
When no workflow is set, until now the current workflow has been chosen. But the workflow we get the artifact from could be another one determined by other criteria like the branch and the artifact name.
We provide a new option `workflow_search`, that if set, allows us to search for the workflow repo-wide according to the other provided data.
This is a failing job with upstream action v3: https://github.com/romangg/theseus-ship/actions/runs/7904208512/job/21573949899
This is a successful job ran against the version from this PR: https://github.com/romangg/theseus-ship/actions/runs/7906156620/job/21581226467
In my case the workflows are named differently depending on them being a scheduled workflow or a workflow on push.
This new option defaulting to `false` should be compatible with …
> Optionally search for workflows

- .github/workflows/download.yml
- main.js
In f6b0bace624032e30a85a8fd9c1a7f8f611f5737 the check on the commit value provided was moved to the body of the function. Instead directly provide it as parameter of the request as it was before, assuming that this might affect the number of requests sent.
> Head sha revert

- .github/workflows/download.yml
- main.js
In commit f6b0bace624032e30a85a8fd9c1a7f8f611f5737 we added a check for !workflow_search before using the current workflow, but with a string this always evaluates to true.
This results in always searching workflows, and if enough inputs are unspecified it can find the wrong run id.
> Read workflow_search input as a boolean

- .github/workflows/download.yml
- main.js
In commit f6b0bace624032e30a85a8fd9c1a7f8f611f5737 we added a check for !workflow_search before using the current workflow, but with a string this always evaluates to true.
This results in always searching workflows, and if enough inputs are unspecified it can find the wrong run id.
> Read workflow_search input as a boolean (#273)

- main.js
It seems that, recently, GitHub has started to return the expired artifact error along with a URL with more documentation. This leads to the equality error condition not being satisfied, and the error to be thrown even when the settings ask for errors to be ignored:
```
Run dawidd6/action-download-artifact@v3
==> Repository: eic/EICrecon
==> Artifact name: docs
==> Local path: publishing_docs/pr/1161/
==> Workflow name: .github/workflows/linux-eic-shell.yml
==> Workflow conclusion: completed
==> Commit: 1705fd8d88312862289bb[27](https://github.com/eic/EICrecon/actions/runs/8314077495/job/22751039311#step:2:28)e8b0642be22104362
==> Allow forks: true
==> (found) Run ID: 7040574340
==> (found) Run date: 2023-11-[30](https://github.com/eic/EICrecon/actions/runs/8314077495/job/22751039311#step: …
```
> fix: accept expired artifacts with documentation url

- README.md
- action.yml
Allowing forks should be false by default as forks can be used to upload malicious artifacts.
Closes #288
> Set allow_forks to false by default

- action.yml
- main.js
Add merge_multiple option to download all artifacts into the same folder. Essentially does the same as the merge-multiple option from the official download action
https://github.com/actions/download-artifact?tab=readme-ov-file#download-multiple-filtered-artifacts-to-the-same-directory
> add merge_multiple option
